config/routes.rb
RailBlogApp::Application.routes.draw do
  devise_for :admins
  devise_for :users

  root 'blogs#index'

  resources :blogs

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validates :title, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 
 def index
  @blogs = Blog.all
 end

 def create
  @blog  = Blog.new(blog_params)

  respond_to do |format|
    if @blog.save
      format.js {
        render :js => "window.location = '#{blogs_path}'"
      }
    else
      format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
  end
 end

 def new
  @blog = Blog.new
 end

 private

  def blog_params
    params.require(:blog).permit(:title, :content, :photo)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-warning"   
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"  
    end
  end

  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
      content_tag("li", attributes, &block)
  end
end

app/helpers/blog_helper.rb
module BlogHelper

end

app/views/blogs/_blog_form.html.haml
#error_explanation.alert.alert-danger.alert-dismissable{style: "display:none;"}
  %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×

  %ul
    - if @blog.errors.any?
      %strong
        = pluralize(@blog.errors.count, "error")
      - @blog.errors.full_messages.each do |msg|
        %li= msg      
.form-group
  = f.label :title
  %br/
  = f.text_field :title , :class => "form-control", :placeholder => 'Title'
.form-group
  = f.label :content
  %br/
  = f.text_area :content , :class => "form-control", :placeholder => 'Tell a Story or Something that you want to say'
.form-group
  = f.label :avatar
  = f.file_field :avatar 
.text-center{style: 'margin-top: 50px;'}
  = f.submit "Publish", class: "btn btn-lg btn-success"        

app/views/blogs/index.html.haml
%header
  .container
    .intro-text
      .intro-lead-in Why So Serious?
      .intro-heading Tell to the world why you are serious.

/ Page Content
.container
  .row
    / Blog Entries Column
    .col-md-8.col-md-offset-2
      %h1.page-header
        List of Stories
        %small Stories that will make you cry why they are so serious

      - for blog in @blogs
        
        %h2
          = blog.title
        %p.lead
          by
          %a{href: "#"} Start Bootstrap
        %p
          %span.glyphicon.glyphicon-time
          Posted on 
          = blog.created_at.strftime("%B %d, %Y")
          = blog.created_at.strftime("%I:%M") + "#{blog.created_at.hour < 12 ? 'AM' : 'PM'}"
        %hr/
        = image_tag blog.photo.url 
        = image_tag blog.photo.url(:medium) 
        = image_tag blog.photo.url(:thumb) 
        %hr/
        %p 
          = blog.content
        %a.btn.btn-success{href: "#"}
          Read More
          %span.glyphicon.glyphicon-chevron-right
        %hr/

      / Pager


  / /.row
  %hr/
  / Footer
  %footer
    .row
      .col-lg-12
        %p Copyright © Your Website 2014
      / /.col-lg-12
    / /.row
/ /.container

app/views/blogs/new.html.haml
.container
  %h2 Create A New Blog
  = form_for(@blog, remote: true, html: { }) do |f| 
    = render partial: 'blog_form', locals: { f: f } 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RailBlogApp
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #wrapper.toggled
      #sidebar-wrapper

        %ul.sidebar-nav
          %li.sidebar-brand
            %a{href: "#"}
              Why So Serious?
          %li
            %a{href: "#"} Home
          %li
            = link_to 'Blogs', '#' 
          - if user_signed_in?
            %li
              = link_to "Sign Out", destroy_user_session_path, :method => :delete
          - else
            .container
              = link_to "Sign In, Now!", new_user_session_path, :class => 'btn btn-default'
            %br            
            .container
              = link_to "Y U No Sign Up?", new_user_registration_path, :class => 'btn btn-success'                           

      %a#menu-toggle.btn.btn-default{href: "#menu-toggle"} 
        %h4 W
      #page-content-wrapper
        = yield

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>